# Generated by Django 3.1.2 on 2020-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('mobile', models.BigIntegerField(default=0)),
                ('occupation', models.TextField(default=None)),
                ('income', models.BigIntegerField(default=0)),
            ],
        ),
    ]
