# Generated by Django 3.1.2 on 2020-11-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familymembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField(default=0)),
                ('purpose', models.TextField(default=None, max_length=120)),
                ('membername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familymembers.familymember')),
            ],
        ),
    ]
