# Generated by Django 3.1.2 on 2020-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familymembers', '0002_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
